version: "3.8"
services:
  api:
    container_name: taf__tasks_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      postgres_migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ${LOGGER_DIR_PATH}:${LOGGER_DIR_PATH_INTERNAL}
    command: [ "poetry", "run", "uvicorn", "app:create_app", "--host", "0.0.0.0", "--port", "5000" ]

  postgres:
    container_name: taf__tasks_postgres
    restart: unless-stopped
    image: postgres:13.1
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5

  postgres_migrations:
    container_name: taf__tasks_postgres__migrations
    build:
      context: .
      dockerfile: docker/postgres_migrations/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: [
      "poetry", "run", "python3", "-m", "scripts.migrate"
    ]